### ISSUE TITLE
Failure creating storage pool on ubuntu 19.10

### ISSUE THREAD

**Issue by velis74** [stackhpc/ansible-role-libvirt-host#24]
Trying to get this role working, but got stuck with:

```
TASK [stackhpc.libvirt-host : Ensure libvirt storage pools are defined] ********************************************************************
failed: [ansible-host] (item={'name': 'default', 'type': 'dir', 'path': '/var/lib/libvirt/images', 'mode': 755, 'owner': 'libvirt-qemu', 'group': 'kvm'}) => {"ansible_loop_var": "item", "changed": false, "item": {"group": "kvm", "mode": 755, "name": "default", "owner": "libvirt-qemu", "path": "/var/lib/libvirt/images", "type": "dir"}, "msg": "The `libvirt` module is not importable. Check the requirements."}
```

Playbook:
```
- name: Basic provisioning of VM hosts
  hosts: vm_hosts
  roles:
    - role: stackhpc.libvirt-host
      libvirt_host_pools:
        - name: default
          type: dir
          path: /var/lib/libvirt/images
          mode: 755
          owner: libvirt-qemu
          group: kvm
      libvirt_host_networks:
        - name: default
          mode: nat
          bridge: virbr0
          domain: qemu.local
          ip: 192.168.123.254
          netmask: 255.255.255.0
          dhcp_start: 192.168.123.100
          dhcp_end: 192.168.123.250
```

A quick internet search shows that mostly this is a result of package dependency misconfiguration in role, but TBH I have no idea how to tackle this. 

Will dig some more, but help would also be appreciated.
