### ISSUE TITLE
Required packages not installed by role

### ISSUE THREAD

**Issue by velis74** [stackhpc/ansible-role-libvirt-host#29]
Just reporting after having finished provisioning using this role.
I had to add the following section to the task provisioning vm hosts:

```
  pre_tasks:
    - name: VM hosts required packages
      apt:
        pkg:
          - python3-libvirt
          - python3-lxml
```

This is ubuntu 18.04 network install with sshd only. The host provisioning step is preceded by some general configuration, including installing some packages already, so I'm not sure if these two are all that is needed.

If these are not installed, various steps within the role will fail at some point or another.
